name: tww3_builder
version: "0.1.0"
profile: tww3_builder

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

vars:
  patch: patch_9.0        # dossier de raw/ à traiter  -> dbt build --vars "patch: patch_9.1"
  raw_root: raw

models:
  tww3_builder:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
    validation:
      +materialized: table
      +schema: validation

seeds:
  tww3_builder:
    +schema: reference
    tests:
      +schema: test_fixtures
